version: "3"
services:
  postgres:
    image: "postgres:11.1-alpine"
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - ../hedgetracker-db-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app
